#!/bin/sh
git submodule update --init --recursive
git submodule update --recursive --remote

cd glfw && cmake . && make && sudo make install
cd ..

sudo apt-get install libboost-all-dev
mkdir VulkanSDK && cd VulkanSDK
wget -c https://sdk.lunarg.com/sdk/download/1.1.92.1/linux/vulkansdk-linux-1.1.92.1.tar.gz -O - | tar -xz
cd ..
